import asyncio
import json
import logging
import re
from typing import Dict, Any, Optional
import httpx
from pydantic import BaseModel, Field
from google import genai
from google.genai import types

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("test-providers")

VALID_ACTIONS = {"CLICK", "TYPE", "SCROLL", "WAIT", "STOP"}

class ActionTarget(BaseModel):
    elementId: Optional[str] = None
    selector: Optional[str] = None
    x: Optional[int] = None
    y: Optional[int] = None

class BrowserAction(BaseModel):
    action: str = Field(description="Must be one of CLICK, TYPE, SCROLL, WAIT, STOP")
    target: Optional[ActionTarget] = None
    value: Optional[str] = None
    reason: str
    providerUsed: str

SYSTEM_PROMPT = """You are an AI Browser Agent that operates strictly on sanitized web page representations and redacted visual previews.
You must decide the single best next action to accomplish the user's task.
Output ONLY a valid JSON object matching this schema:
{
  "action": "CLICK" | "TYPE" | "SCROLL" | "WAIT" | "STOP",
  "target": {
    "elementId": "<id of target element>",
    "selector": "<css selector if available>"
  },
  "value": "<text to type if action is TYPE, or null>",
  "reason": "<short explanation of why this action was chosen>"
}
Do not wrap in markdown or extra text, output purely the JSON object."""

def extract_json(raw_text: str, provider_name: str) -> BrowserAction:
    cleaned = raw_text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"```$", "", cleaned)
        cleaned = cleaned.strip()

    match = re.search(r"(\{.*\})", cleaned, re.DOTALL)
    if match:
        cleaned = match.group(1)

    parsed = json.loads(cleaned)
    action_type = str(parsed.get("action") or "STOP").upper()
    if action_type not in VALID_ACTIONS:
        logger.warning(f"Unrecognized action '{action_type}', defaulting to STOP")
        action_type = "STOP"

    target_data = parsed.get("target")
    target_obj = None
    if isinstance(target_data, dict):
        target_obj = ActionTarget(
            elementId=target_data.get("elementId"),
            selector=target_data.get("selector"),
            x=target_data.get("x"),
            y=target_data.get("y"),
        )

    return BrowserAction(
        action=action_type,
        target=target_obj,
        value=parsed.get("value"),
        reason=parsed.get("reason", f"Action generated by {provider_name}"),
        providerUsed=provider_name,
    )

async def test_hf_direct(token: str, model_name: str):
    prompt_text = (
        f"User Task: search for striver\n\n"
        f"Sanitized Page Title: (9) YouTube\n"
        f"Available Interactive Elements:\n"
        f"[\n  {{\n    \"id\": \"el_search_input\",\n    \"tag\": \"input\",\n    \"type\": \"text\",\n    \"label\": \"Search\",\n    \"selector\": \"input#search\"\n  }}\n]\n"
    )
    url = "https://router.huggingface.co/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model_name,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt_text},
        ],
        "temperature": 0.1,
        "max_tokens": 512,
    }

    async with httpx.AsyncClient(timeout=30.0) as client:
        res = await client.post(url, headers=headers, json=payload)
        res.raise_for_status()
        data = res.json()
        raw_content = data["choices"][0]["message"]["content"]
        return extract_json(raw_content, "huggingface")

async def test_gemini_direct(api_key: str, model_name: str):
    client = genai.Client(api_key=api_key)
    prompt_text = (
        f"{SYSTEM_PROMPT}\n\n"
        f"User Task: search for striver\n\n"
        f"Sanitized Page Title: (9) YouTube\n"
        f"Available Interactive Elements:\n"
        f"[\n  {{\n    \"id\": \"el_search_input\",\n    \"tag\": \"input\",\n    \"type\": \"text\",\n    \"label\": \"Search\",\n    \"selector\": \"input#search\"\n  }}\n]\n"
    )
    
    # Try specified model or fallback candidates
    candidates = [
        model_name,
        "gemini-3.1-flash-lite",
        "gemini-3-flash-preview",
        "gemini-3.5-flash-lite",
        "gemini-3.1-flash-lite-preview",
        "gemini-3.7-flash",
    ]
    last_err = None
    for cand in candidates:
        try:
            resp = client.models.generate_content(
                model=cand,
                contents=[prompt_text],
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    temperature=0.1,
                ),
            )
            raw = resp.text or ""
            return extract_json(raw, "gemini")
        except Exception as e:
            last_err = e
            continue
    raise last_err

async def main():
    from config import settings
    print("HF Token present:", bool(settings.HF_TOKEN))
    print("Gemini Key present:", bool(settings.GEMINI_API_KEY))

    # Test HF with Qwen 2.5 VL
    print("\n--- Testing Hugging Face ---")
    try:
        hf_model = "Qwen/Qwen2.5-VL-72B-Instruct"
        hf_action = await test_hf_direct(settings.HF_TOKEN, hf_model)
        print("HF Action successfully generated:")
        print(hf_action.model_dump_json(indent=2))
    except Exception as e:
        print("HF Error:", e)

    # Test Gemini
    print("\n--- Testing Gemini ---")
    try:
        gemini_action = await test_gemini_direct(settings.GEMINI_API_KEY, settings.GEMINI_MODEL)
        print("Gemini Action successfully generated:")
        print(gemini_action.model_dump_json(indent=2))
    except Exception as e:
        print("Gemini Error:", e)

if __name__ == "__main__":
    asyncio.run(main())
